# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/sethj

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	KyndeBlade-Android-DebugGame  \
	KyndeBlade-Android-Development  \
	KyndeBlade-Android-Shipping  \
	KyndeBlade-Linux-DebugGame  \
	KyndeBlade-Linux-Development  \
	KyndeBlade-Linux-Shipping  \
	KyndeBlade-LinuxArm64-DebugGame  \
	KyndeBlade-LinuxArm64-Development  \
	KyndeBlade-LinuxArm64-Shipping  \
	KyndeBlade \
	KyndeBladeEditor-Linux-DebugGame  \
	KyndeBladeEditor-Linux-Development  \
	KyndeBladeEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend KyndeBladeEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug KyndeBladeEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

KyndeBlade-Android-DebugGame:
	 $(BUILD) KyndeBlade Android DebugGame  -Project="/home/sethj/KyndeBlade/KyndeBlade.uproject" $(ARGS)

KyndeBlade-Android-Development:
	 $(BUILD) KyndeBlade Android Development  -Project="/home/sethj/KyndeBlade/KyndeBlade.uproject" $(ARGS)

KyndeBlade-Android-Shipping:
	 $(BUILD) KyndeBlade Android Shipping  -Project="/home/sethj/KyndeBlade/KyndeBlade.uproject" $(ARGS)

KyndeBlade-Linux-DebugGame:
	 $(BUILD) KyndeBlade Linux DebugGame  -Project="/home/sethj/KyndeBlade/KyndeBlade.uproject" $(ARGS)

KyndeBlade-Linux-Development:
	 $(BUILD) KyndeBlade Linux Development  -Project="/home/sethj/KyndeBlade/KyndeBlade.uproject" $(ARGS)

KyndeBlade-Linux-Shipping:
	 $(BUILD) KyndeBlade Linux Shipping  -Project="/home/sethj/KyndeBlade/KyndeBlade.uproject" $(ARGS)

KyndeBlade-LinuxArm64-DebugGame:
	 $(BUILD) KyndeBlade LinuxArm64 DebugGame  -Project="/home/sethj/KyndeBlade/KyndeBlade.uproject" $(ARGS)

KyndeBlade-LinuxArm64-Development:
	 $(BUILD) KyndeBlade LinuxArm64 Development  -Project="/home/sethj/KyndeBlade/KyndeBlade.uproject" $(ARGS)

KyndeBlade-LinuxArm64-Shipping:
	 $(BUILD) KyndeBlade LinuxArm64 Shipping  -Project="/home/sethj/KyndeBlade/KyndeBlade.uproject" $(ARGS)

KyndeBlade: KyndeBlade-Linux-Development

KyndeBladeEditor-Linux-DebugGame:
	 $(BUILD) KyndeBladeEditor Linux DebugGame  -Project="/home/sethj/KyndeBlade/KyndeBlade.uproject" $(ARGS)

KyndeBladeEditor-Linux-Development:
	 $(BUILD) KyndeBladeEditor Linux Development  -Project="/home/sethj/KyndeBlade/KyndeBlade.uproject" $(ARGS)

KyndeBladeEditor: KyndeBladeEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/sethj/KyndeBlade/KyndeBlade.uproject" -Game 

.PHONY: $(TARGETS)
