#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "CombatAction.generated.h"

UENUM(BlueprintType)
enum class ECombatActionType : uint8
{
	Attack,
	Dodge,
	Parry,
	Counter,
	Special,
	Wait
};

USTRUCT(BlueprintType)
struct FCombatActionData
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	ECombatActionType ActionType;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Damage = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float StaminaCost = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float SuccessWindow = 0.0f; // Time window for real-time mechanics (dodge/parry)

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float CastTime = 0.0f; // Time before action executes

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float ExecutionTime = 0.0f; // Time after action executes before turn ends

	// Expedition 33-inspired: AP/Virtue Points system
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float VirtuePointsGenerated = 0.0f; // AP generated by this action (melee attacks)

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float VirtuePointsCost = 0.0f; // AP cost of this action (ranged/skills)

	// Expedition 33-inspired: Break system
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float BreakDamage = 0.0f; // Break damage dealt by this action

	// Expedition 33-inspired: Elemental system
	UENUM(BlueprintType)
	enum class EElementType : uint8
	{
		None,
		Flamme,    // Fire
		Frost,     // Ice
		Thunder,   // Lightning
		Trewthe,   // Holy/Truth
		Fals,      // Dark/False
		Kynde      // Nature
	};

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	EElementType ElementType = EElementType::None;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString ActionName;

	FCombatActionData()
	{
		ActionType = ECombatActionType::Wait;
		Damage = 0.0f;
		StaminaCost = 0.0f;
		SuccessWindow = 0.0f;
		CastTime = 0.0f;
		ExecutionTime = 0.0f;
		VirtuePointsGenerated = 0.0f;
		VirtuePointsCost = 0.0f;
		BreakDamage = 0.0f;
		ElementType = EElementType::None;
		ActionName = TEXT("Wait");
	}
};

/**
 * Base class for combat actions
 */
UCLASS(BlueprintType, Blueprintable)
class KYNDEBLADE_API UCombatAction : public UObject
{
	GENERATED_BODY()

public:
	UCombatAction();

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FCombatActionData ActionData;

	UFUNCTION(BlueprintCallable)
	virtual void ExecuteAction(class AMedievalCharacter* Executor, class AMedievalCharacter* Target);

	UFUNCTION(BlueprintCallable)
	float GetCastTime() const { return ActionData.CastTime; }

	UFUNCTION(BlueprintCallable)
	float GetExecutionTime() const { return ActionData.ExecutionTime; }

	UFUNCTION(BlueprintCallable)
	float GetVirtuePointsGenerated() const { return ActionData.VirtuePointsGenerated; }

	UFUNCTION(BlueprintCallable)
	float GetVirtuePointsCost() const { return ActionData.VirtuePointsCost; }

	UFUNCTION(BlueprintCallable)
	float GetBreakDamage() const { return ActionData.BreakDamage; }

	UFUNCTION(BlueprintCallable)
	EElementType GetElementType() const { return ActionData.ElementType; }

	UFUNCTION(BlueprintImplementableEvent)
	void OnActionExecuted(AMedievalCharacter* Executor, AMedievalCharacter* Target);

protected:
	UFUNCTION(BlueprintCallable)
	virtual bool CanExecute(AMedievalCharacter* Executor);
};
