#!/bin/bash
# Script to download Epic Games Launcher for Linux

echo "Epic Games Launcher Download Instructions"
echo "=========================================="
echo ""
echo "The Epic Games Launcher for Linux must be downloaded from:"
echo "  https://www.unrealengine.com/en-US/download"
echo ""
echo "Steps:"
echo "1. Visit: https://www.unrealengine.com/en-US/download"
echo "2. Click 'Download Now'"
echo "3. Select Linux version"
echo "4. Download the .AppImage or .sh installer"
echo "5. Make it executable: chmod +x EpicGamesLauncher-*.AppImage"
echo "6. Run it: ./EpicGamesLauncher-*.AppImage"
echo ""
echo "Alternatively, you can download directly using:"
echo "  wget -O EpicGamesLauncher.AppImage 'https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncher.AppImage'"
echo ""
echo "After installing the launcher:"
echo "1. Launch it and sign in to your Epic Games account"
echo "2. Go to 'Unreal Engine' tab"
echo "3. Click 'Install Engine'"
echo "4. Select version 5.7.1"
echo "5. Choose installation location"
echo "6. Wait for installation to complete (~20-30GB download)"
