#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "CombatAction.generated.h"

UENUM(BlueprintType)
enum class ECombatActionType : uint8
{
	Strike,      // Attack - Piers Plowman: "Sothfastnesse's Stroke" (Truth's Strike)
	Escapade,    // Dodge - Piers Plowman: "Kynde's Evasion" (Nature's Evasion)
	Ward,        // Parry - Piers Plowman: "Trewthe's Sheeld" (Truth's Shield)
	Counter,     // Counter-attack - Piers Plowman: Counter-strike
	Guard,       // Reduce incoming damage, restore stamina
	Special,     // Special actions - Various Piers-themed abilities
	Rest         // Wait - Piers Plowman: "Kynde's Rest" (Nature's Rest)
};

UENUM(BlueprintType)
enum class EKyndeElementType : uint8
{
	None,
	Flamme,    // Fire
	Frost,     // Ice
	Thunder,   // Lightning
	Trewthe,   // Holy/Truth
	Fals,      // Dark/False
	Kynde      // Nature
};

USTRUCT(BlueprintType)
struct FCombatActionData
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	ECombatActionType ActionType;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Damage = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float StaminaCost = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float ManaCost = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float SuccessWindow = 0.0f; // Time window for real-time mechanics (Escapade/Ward)

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float CastTime = 0.0f; // Time before action executes

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float ExecutionTime = 0.0f; // Time after action executes before turn ends

	// Expedition 33-inspired: Kynde system
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float KyndeGenerated = 0.0f; // Kynde generated by this action (melee attacks)

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float KyndeCost = 0.0f; // Kynde cost of this action (ranged/skills)

	// Expedition 33-inspired: Break system
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float BreakDamage = 0.0f; // Break damage dealt by this action

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	EKyndeElementType ElementType = EKyndeElementType::None;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString ActionName;

	FCombatActionData()
	{
		ActionType = ECombatActionType::Rest;
		Damage = 0.0f;
		StaminaCost = 0.0f;
		ManaCost = 0.0f;
		SuccessWindow = 0.0f;
		CastTime = 0.0f;
		ExecutionTime = 0.0f;
		KyndeGenerated = 0.0f;
		KyndeCost = 0.0f;
		BreakDamage = 0.0f;
		ElementType = EKyndeElementType::None;
		ActionName = TEXT("Kyndes Rest");
	}
};

/**
 * Base class for combat actions
 */
UCLASS(BlueprintType, Blueprintable)
class KYNDEBLADE_API UCombatAction : public UObject
{
	GENERATED_BODY()

public:
	UCombatAction();

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FCombatActionData ActionData;

	UFUNCTION(BlueprintCallable)
	virtual void ExecuteAction(class AMedievalCharacter* Executor, class AMedievalCharacter* Target);

	/** When true, Strike does not apply damage (TurnManager will apply after real-time window). */
	UFUNCTION(BlueprintCallable)
	virtual void ExecuteActionWithDeferredDamage(class AMedievalCharacter* Executor, class AMedievalCharacter* Target);

	UFUNCTION(BlueprintCallable)
	float GetCastTime() const { return ActionData.CastTime; }

	UFUNCTION(BlueprintCallable)
	float GetExecutionTime() const { return ActionData.ExecutionTime; }

	UFUNCTION(BlueprintCallable)
	float GetKyndeGenerated() const { return ActionData.KyndeGenerated; }

	UFUNCTION(BlueprintCallable)
	float GetKyndeCost() const { return ActionData.KyndeCost; }

	UFUNCTION(BlueprintCallable)
	float GetBreakDamage() const { return ActionData.BreakDamage; }

	UFUNCTION(BlueprintCallable)
	EKyndeElementType GetElementType() const { return ActionData.ElementType; }

	UFUNCTION(BlueprintImplementableEvent)
	void OnActionExecuted(AMedievalCharacter* Executor, AMedievalCharacter* Target);

protected:
	UFUNCTION(BlueprintCallable)
	virtual bool CanExecute(AMedievalCharacter* Executor);
};
